name: フロント開発issue
description: フロント開発がメインのissueを記載します。
labels: ["frontend"]
body:
  - type: markdown
    attributes:
      value: |
        下記に詳細を記載していく
  - type: textarea
    id: relate-issues
    attributes:
      label: "関連タスク"
      description: "関連するBacklogやissueを記載"
      placeholder: |
        - Backlogタスク
        - issue番号
  - type: textarea
    id: task-lists
    attributes:
      label: "概要"
      description: "概要・作業内容を記載"
      value: |
        ### 概要
        軽く概要を記載する。
        ### 問題点
        問題点を記載 (〇〇のAPIが通らないなど)
        ### 再現手順 >
        あれば
        ### 作業内容
        - [ ] 作業内容A
        - [ ] 作業内容B
    validations:
      required: true
  - type: dropdown
    id: target_merge
    attributes:
      label: "マージ先"
      description: "どこに反映するか"
      multiple: true
      options:
        - develop
        - master
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      options:
        - "Low"
        - "Middle"
        - "High"
        - "Hotfix"
    validations:
      required: true
  - type: textarea
    id: reference
    attributes:
      label: "参考資料"
      description: "詳細設計書やAPI仕様書などを記載する"
      value: |
        - [詳細設計書](https://docs.google.com/spreadsheets/d/1t2xVWyUr_y6Z-fVJGMUjGYLrdNXgWSEgwWVzYSmAusc/edit#gid=202444758)
        - [API仕様書](https://docs.google.com/spreadsheets/d/1JSEEHsOEMjpelx7u-nnOu9w_SQeiGJDFeZXdHzgnR44/edit#gid=1285434987)
        - [テーブル定義書](https://docs.google.com/spreadsheets/d/1ENnFUOWqg0beAJjn75fhiWx56wp7eEzXpetHqyL1TZk/edit#gid=0)
        - [その他資料](https://github.com/seeds-std/robo_check/wiki)