name: フロント開発issue
description: フロント開発がメインのissueを記載します。
labels: ["frontend"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: "概要"
      description: "概要を記載してください"
      placeholder: "何か"
    validations:
      required: true
  - type: checkboxes
    id: target_merge
    attributes:
      label: "マージ先"
      description: What version of our software are you running?
      options:
        - label: develop
        - label: master
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: このタスクの優先度は？
      options:
        - "Low"
        - "Middle"
        - "High"
        - "Hotfix"
    validations:
      required: true