name: フロント開発issue
description: フロント開発がメインのissueを記載します。
labels: ["frontend"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: "概要"
      description: "概要を記載してください"
      placeholder: "何か"
    validations:
      required: true
  - type: checkboxes
    id: target_merge
    attributes:
      label: "マージ先"
      description: What version of our software are you running?
      options:
        - label: bbb
        - label: aaa
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - "優先度 低"
        - "優先度 中"
        - "優先度 高"