sequenceDiagram
    autonumber
    actor customer as 顧客
    participant robocheck_fe as ロボチェック<br>フロントエンド
    participant robocheck_be as ロボチェック<br>バックエンド
    participant with_secure as ウィルスチェック
    participant robocheck_db as ロボDB
    participant nyuko_file_efs as 入稿ファイル<br>EFS
    participant nyuko_file_s3 as 入稿ファイル<br>S3
    participant prefright_s3 as プリフライト<br>S3
    participant asura_log_s3 as Asuraログ<br>S3
    participant asura_link as Asura/AsuraLink

    %% 複数ページ取得
    robocheck_fe ->>+ robocheck_be: 複数ページ取得
    robocheck_be ->>+ robocheck_db: 依頼番号の取得
    robocheck_db -->>- robocheck_be: 結果を返却
    robocheck_be ->>+ prefright_s3: 複数ページを取得
    prefright_s3 -->>- robocheck_be: ページ画像を返却
    robocheck_be -->>- robocheck_fe: レスポンスを返却
    robocheck_fe ->> customer: 事前プレビュー画面を表示
    %% 事前プレビュー
    opt 注文ページが2ページ以上ある場合
        customer --)+ robocheck_fe: 表裏の入れ替え
        robocheck_fe --)- customer: ページ表示
    end
    customer --)+ robocheck_fe: 天地入れ替え
    robocheck_fe --)- customer: ページ表示
    customer --)+ robocheck_fe: 縦横の変更
    robocheck_fe --)- customer: ページ表示
    customer ->>+ robocheck_fe: データチェック開始
    robocheck_fe ->>+ robocheck_be: 変換情報の送信
    robocheck_be ->>+ asura_link: ExecPrefright 4回目 Dルート
    asura_link -->>- robocheck_be: レスポンスを返却
    asura_link --)+ asura_log_s3: ログ出力
    asura_log_s3 --)- asura_link: OK
    asura_link --)+ prefright_s3: 仕上がり画像を出力
    prefright_s3 --)- asura_link: OK
    asura_link --)+ prefright_s3: 塗り足し画像を出力
    prefright_s3 --)- asura_link: OK
    asura_link --)+ prefright_s3: 印刷用PDFを出力
    prefright_s3 --)- asura_link: OK
    asura_link --)+ prefright_s3: 印刷用PNGを出力
    prefright_s3 --)- asura_link: OK
    asura_link --)+ prefright_s3: DL用PDFを出力
    prefright_s3 --)- asura_link: OK
    loop ログが取得できるまで
        robocheck_be ->>+ asura_log_s3: ログを取得
        asura_log_s3 -->>- robocheck_be: XHTMLを返却
    end
    robocheck_be ->>+ robocheck_db: 依頼番号を保存
    robocheck_db -->>- robocheck_be: OK
    robocheck_be ->> robocheck_be: XHTMLの解析
    robocheck_be ->> robocheck_be: データチェック項目の抽出
    robocheck_be ->>+ prefright_s3: 印刷用PNGの取得
    prefright_s3 ->>- robocheck_be: 電子署名付きURLを返却
    robocheck_be -->>- robocheck_fe: レスポンスを返却
    robocheck_fe -->>- customer: データチェック結果画面を表示
