sequenceDiagram
    autonumber
    actor customer as 顧客
    participant renkei_site as 連携元ECサイト
    participant robocheck_be as ロボチェック<br>バックエンド
    participant with_secure as ウィルスチェック
    participant robocheck_db as ロボDB
    participant nyuko_file_efs as 入稿ファイル<br>EFS
    participant nyuko_file_s3 as 入稿ファイル<br>S3(ロボ)
    participant nyuko_file_s3_asura as 入稿ファイル<br>S3(asura)
    participant comp_api as カンプ

    %% 入稿完了の処理
    renkei_site ->> renkei_site: 入稿完了の処理
    renkei_site ->>+ robocheck_be: アップロードファイルの取得
    %% カンプAPI
    robocheck_be ->>+ robocheck_db: 展開、仕上がりサイズの取得
    robocheck_db -->>- robocheck_be: 結果を返却
    robocheck_be ->>+ robocheck_db: 直近の依頼番号を取得
    robocheck_db -->>- robocheck_be: 依頼番号を返却
    robocheck_be ->>+ comp_api: カンプAPIを発行
    comp_api -->>- robocheck_be: 結果を返却
    %% アップロードファイル
    robocheck_be ->>+ nyuko_file_s3_asura: 入稿ファイルを取得
    nyuko_file_s3_asura -->>- robocheck_be: ファイルを返却
    robocheck_be ->>+ nyuko_file_efs: 一時的にアップロード
    nyuko_file_efs -->>- robocheck_be: OK
    robocheck_be ->> robocheck_be: ZIPファイルにまとめる
    robocheck_be ->>+ nyuko_file_s3: ZIPファイルをアップロード
    nyuko_file_s3 -->>- robocheck_be: OK
    robocheck_be ->>+ nyuko_file_s3: ZIPファイルを取得
    nyuko_file_s3 -->>- robocheck_be: 電子署名付きURLを返却
    robocheck_be -->>- renkei_site: レスポンスを返却
    renkei_site ->>+ nyuko_file_s3: 入稿ファイルをダウンロード
    nyuko_file_s3 -->>- renkei_site: ファイルを返却
    renkei_site ->> renkei_site: 入稿処理
    renkei_site ->> customer: 入稿完了画面を表示
